apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-movie-app-api-deployment
  labels:
    app: docker-k8s-movie-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: duda973/first-repo
          ports:
            - containerPort: 8080

