apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjEzIChkYXJ3aW4pIgoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImV4cGVyaW1lbnRhbCI6ICJkaXNhYmxlZCIsCgkic3RhY2tPcmNoZXN0cmF0b3IiOiAic3dhcm0iCn0=
kind: Secret
metadata:
  creationTimestamp: "2020-12-18T19:28:45Z"
  name: regcred
  namespace: duda973
  resourceVersion: "268867929"
  selfLink: /api/v1/namespaces/duda973/secrets/regcred
  uid: 2a1a2708-fa1c-4c61-9b8e-e0d5d7fda800
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviebase-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviebase-api
  template:
    metadata:
      labels:
        app: moviebase-api
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: duda973/moviebase:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: moviebase-api-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: moviebase-api
spec:
  type: ClusterIP
  ports:
    - name: moviebase-api
      port: 8080
  selector:
    app: moviebase-api
