apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-movie-app-api-deployment
spec:
  selector:
    matchLabels:
      app: docker-k8s-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: okteto.dev/docker-k8s-demo:latest
          ports:
            - containerPort: 8080